export const FacebookURL = 'https://www.facebook.com/bibek.koirala.583?mibextid=LQQJ4d'
export const GithubURL = 'https://github.com/BibekKoirala'
export const InstagramURL = 'https://www.instagram.com/kbibek371?igsh=MWJhdjRrbzRleHE1Yw%3D%3D&utm_source=qr'
export const TwitterURL = 'https://x.com/bibek_koi?s=21'
export const LinkedinURL = 'https://www.linkedin.com/in/bibek-koirala-b4b1b9243?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app'
